title: DjangoCon Africa 2023
email: hello@djangocon.africa
# Add host country and also update the date for the conference in the config.yml file
description: |
  DjangoCon Africa 2023 conference will take place in 
  from November 6-11, 2023!
enforce_ssl: "2023.djangocon.africa"
baseurl: ""
url: "https://2023.djangocon.africa"
twitter_username: djcafrica
logo: /static/img/site/logo.svg
footer_logo: /static/img/site/footer-logo.svg
relative_permalinks: false
permalink: news/:title/
default_banner: /static/img/site/about_img.png

# Build settings
markdown: kramdown

future: true

include:
  - _pages
  - static

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-redirect-from


collections:  
  organizers:
    output: false
    permalink: /:collection/
  sponsors:
    output: false
    permalink: /:collection/
  speakers:
    output: false
    permalink: /:collection/
  

# Our DjangoCon Africa settings...
year: 2023 
conference_duration_days: 6
conference_dates:  6 - 11 of November 2023
host_city_and_country: Zanzibar, Tanzania
location: State University of Zanzibar
conduct_email: "conduct@djangocon.africa"
conduct_phone: ""
contact_us_email: "hello@djangocon.africa"
opportunity_grants_email: "grants@djangocon.africa"
program_team_email: "program@djangocon.africa"
sponsors_email: "sponsors@djangocon.africa"
visa_email: "visas@djangocon.africa"

coc_team:
- Anna Makarudze
- Daniele Procida
- Jessica Upani
- Humphrey Butau
- Abigail Dogbe


# Our DjangoCon Africa Links
cfp: ""
slack: ""
opportunity_grant_application: ""
sponsorship_prospectus: ""
ticket_link: ""

# DjangoCons
djc_us: "https://djangocon.us"
djc_eu: "https://djangocon.eu"
djc_au: "https://djangocon.com.au"

# DjangoCon Africa Social Links
twitter: "https://twitter.com/djcafrica"
facebook: "https://www.facebook.com/djcafrica/"
instagram: "https://www.instagram.com/djcafrica/"
github: "https://github.com/djangocon"


# social links
t: "https://twitter.com"
g: "https://github.com"
l: "https://linkedin.com/in"

